ahoyapi: v2
usage: Smart Home cli tools.
commands:
  docker:
    usage: A series of docker commands (experimental)
    imports:
      - .ahoy/docker.ahoy.yml

  do:
    usage: Digital Ocean commands
    imports:
      - .ahoy/do.ahoy.yml

  ansible:
    usage: Ansible commands
    imports:
      - .ahoy/ansible.ahoy.yml

  qa:
    usage: Quality Assurance commands
    imports:
      - .ahoy/qa.ahoy.yml
